
export const actionTypes = {

  DOWNLOAD_XLS: 'DOWNLOAD_XLS',
  CREATE_TRANSACTION: 'CREATE_TRANSACTION',

  SHOW_DEATAILS: 'DEATAILS',

  CHANGE_PAGE: 'CHANGE_PAGE',
  GET_PREV_PAGE: 'GET_PREV_PAGE',
  GET_NEXT_PAGE: 'GET_NEXT_PAGE',
}
